//Creating infinite loop using for loop
class InfiniteForLoop{
	public static void main(String[] papan) {
		for (; ; ) {
			System.out.println("Towards Infinity");
		}
	}
}

/*
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity
Towards Infinity

*/